### ISSUE TITLE
Formbricks widget not working with HTML5 script

### ISSUE THREAD

**Issue by Sixth2538** [formbricks/formbricks#215]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Unable to embed formbricks widget to website running on dockerized ghost CMS. 

### Steps to Reproduce

1. Self-hosted dockerized Ghost CMS and Formbricks
2. Connecting to both successfully over https
3. Copied HTML5 code from formbricks instance over to Ghost CMS site header via Code Injection

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
-->

## Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [x ] self-hosted formbricks, version/commit: [v0.8]

### Additional Context

Log from formbricks docker container:
```
ReferenceError: window is not defined
    at SetupInstructions (/home/nextjs/apps/web/.next/server/app/environments/[environmentId]/settings/setup/page.js:1124:17)
    at renderWithHooks (/home/nextjs/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8385:16)
    at renderIndeterminateComponent (/home/nextjs/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8459:15)
    at renderElement (/home/nextjs/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8694:7)
    at renderLazyComponent (/home/nextjs/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8674:3)
    at renderElement (/home/nextjs/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8784:11)
    at renderNodeDestructiveImpl (/home/nextjs/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8862:11)
    at renderNodeDestructive (/home/nextjs/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8834:14)
    at renderNode (/home/nextjs/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9018:12)
    at renderChildrenArray (/home/nextjs/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8970:7)
```

Log from ghost docker container:
```
[2023-03-31 07:39:00] INFO "GET /dist/index.umd.js" 301 3ms
[2023-03-31 07:39:00] INFO "GET /dist/index.umd.js/" 404 8ms
```

**Comment by mattinannt** [comment]
@Sixth2538 we are currently fixing an issue with the widget that could be related to your problems.
When exactly did the error occur and where. From your logs it looks like the Setup Instructions page in the Formbricks App stopped working?

**Comment by Sixth2538** [comment]
Its working now, thanks for the swift response!
