### ISSUE TITLE
[BUG] oAuth lost on prod env but work on dev env

### ISSUE THREAD

**Issue by bnmg** [formbricks/formbricks#2409]
### Issue Summary

Faced the subject with no idea what happen.
Tried revoke secret and regenerate on google API level, update in caprover ENV(KEY:VALUE), restart instance, delete and connect formbricks app from connected apps on google account side, delete cookies, etc... 
Nothing helps to access Integration connection which was earlier connected to Google sheet! 

Yet! It is shown as 🟢  Active Connection in Integration dashboard.

### Steps to Reproduce

1. installed caprover's docker image, enroll all the ENV settings (google oauth, s3 etc)
2. used `Production` environment by selecting it in formbricks UI, created Teams and Products linked to them
3. created 'link' type of survey in two Teams in two Surveys and connected both to google sheet through `Integration` tab, and everything worked well, tada populated to both google sheets
4. within some time pass (a week may be) one of Surveys stopped populating data and render an Error Message while the connection remains Active as it is indicated

![image](https://github.com/formbricks/formbricks/assets/991907/c7f464b5-de53-4445-8a97-7f6666c70ca7)

if I press `Manage Sheets` this appears,
and no matter which Product I am - pressing `Go to Dashboard` brings me to root 

```
Error loading resources
This resource doesn't exist or you don't have the necessary rights to access it.
```
![image](https://github.com/formbricks/formbricks/assets/991907/0690aa73-3fd0-4fdd-9cb6-6c84890271cb)

6. once I pressed and Error appears the server logs renders this
```
2024-04-07T20:15:22.310232649Z a [Error]: invalid_grant
2024-04-07T20:15:22.310299765Z at P._request (/home/nextjs/apps/web/.next/server/chunks/2851.js:1:27384)
2024-04-07T20:15:22.310309613Z at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-07T20:15:22.310314663Z at async m.refreshTokenNoCache (/home/nextjs/apps/web/.next/server/chunks/2851.js:10:44791)
2024-04-07T20:15:22.310321606Z at async m.getRequestMetadataAsync (/home/nextjs/apps/web/.next/server/chunks/2851.js:10:47220)
2024-04-07T20:15:22.310326035Z at async m.requestAsync (/home/nextjs/apps/web/.next/server/chunks/2851.js:10:48314)
2024-04-07T20:15:22.310331154Z at async f (/home/nextjs/apps/web/.next/server/app/(app)/environments/[environmentId]/integrations/google-sheets/page.js:20:55902)
2024-04-07T20:15:22.310352504Z at async g (/home/nextjs/apps/web/.next/server/app/(app)/environments/[environmentId]/integrations/google-sheets/page.js:20:56182)
2024-04-07T20:15:22.310357093Z at async g (/home/nextjs/apps/web/.next/server/app/(app)/environments/[environmentId]/integrations/google-sheets/page.js:1:26714) {
2024-04-07T20:15:22.310361511Z config: {
2024-04-07T20:15:22.310365078Z method: 'POST',
2024-04-07T20:15:22.310368664Z url: 'https://oauth2.googleapis.com/token',
2024-04-07T20:15:22.310372662Z data: '<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.',
2024-04-07T20:15:22.310377020Z headers: {
2024-04-07T20:15:22.310380627Z 'Content-Type': 'application/x-www-form-urlencoded',
2024-04-07T20:15:22.310384354Z 'User-Agent': 'google-api-nodejs-client/9.4.1',
2024-04-07T20:15:22.310387911Z 'x-goog-api-client': 'gl-node/20.11.1'
2024-04-07T20:15:22.310391437Z },
2024-04-07T20:15:22.310394893Z paramsSerializer: [Function: paramsSerializer],
2024-04-07T20:15:22.310398520Z body: '<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.',
2024-04-07T20:15:22.310402488Z validateStatus: [Function: validateStatus],
2024-04-07T20:15:22.310406065Z responseType: 'unknown',
2024-04-07T20:15:22.310410493Z errorRedactor: [Function: e]
2024-04-07T20:15:22.310414009Z },
2024-04-07T20:15:22.310417476Z response: {
2024-04-07T20:15:22.310420962Z config: {
2024-04-07T20:15:22.310424439Z method: 'POST',
2024-04-07T20:15:22.310427946Z url: 'https://oauth2.googleapis.com/token',
2024-04-07T20:15:22.310431522Z data: '<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.',
2024-04-07T20:15:22.310435300Z headers: [Object],
2024-04-07T20:15:22.310438826Z paramsSerializer: [Function: paramsSerializer],
2024-04-07T20:15:22.310442373Z body: '<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.',
2024-04-07T20:15:22.310446060Z validateStatus: [Function: validateStatus],
2024-04-07T20:15:22.310449616Z responseType: 'unknown',
2024-04-07T20:15:22.310453113Z errorRedactor: [Function: e]
2024-04-07T20:15:22.310456629Z },
2024-04-07T20:15:22.310460126Z data: {
2024-04-07T20:15:22.310463602Z error: 'invalid_grant',
2024-04-07T20:15:22.310468211Z error_description: 'Token has been expired or revoked.'
2024-04-07T20:15:22.310471838Z },
2024-04-07T20:15:22.310475384Z headers: {
2024-04-07T20:15:22.310478941Z 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
2024-04-07T20:15:22.310487547Z 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
2024-04-07T20:15:22.310491265Z 'content-encoding': 'gzip',
2024-04-07T20:15:22.310494911Z 'content-type': 'application/json; charset=utf-8',
2024-04-07T20:15:22.310498899Z date: 'Sun, 07 Apr 2024 20:15:22 GMT',
2024-04-07T20:15:22.310502426Z expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
2024-04-07T20:15:22.310505962Z pragma: 'no-cache',
2024-04-07T20:15:22.310509459Z server: 'scaffolding on HTTPServer2',
2024-04-07T20:15:22.310512985Z 'transfer-encoding': 'chunked',
2024-04-07T20:15:22.310516502Z vary: 'Origin, X-Origin, Referer',
2024-04-07T20:15:22.310520028Z 'x-content-type-options': 'nosniff',
2024-04-07T20:15:22.310523565Z 'x-frame-options': 'SAMEORIGIN',
2024-04-07T20:15:22.310527061Z 'x-xss-protection': '0'
2024-04-07T20:15:22.310530578Z },
2024-04-07T20:15:22.310534025Z status: 400,
2024-04-07T20:15:22.310537511Z statusText: 'Bad Request',
2024-04-07T20:15:22.310541018Z request: { responseURL: 'https://oauth2.googleapis.com/token' }
2024-04-07T20:15:22.310544714Z },
2024-04-07T20:15:22.310548171Z error: undefined,
2024-04-07T20:15:22.310551788Z status: 400
2024-04-07T20:15:22.310555354Z }

```

By selecting `Development` / `Production` switchable in dashboard UI 
![image](https://github.com/formbricks/formbricks/assets/991907/43b0667b-77dc-4949-afa3-7badf7c7dc75)

- I can connect and disconnect easily some new Surveys once I created new `Product` item and added there new `Survey` 

ℹ️ 🧠   It seems something happen with `Product` entity to `Environment` level...

I found if I  switch to another Product within the same Production UI env - Integration shows Not Connected.
So I can connect and disconnect smoothly.
And it work. But not that first initial Product I've connected earlier. So I can't disconnect it.

### Expected behavior

If I see Active Google Sheet Integration (what is indicated as Active) it has to be easily to connect and disconnect. As with other Products in the same formbricks docker Teams.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: sentos9
- Node: v18.17.1
- npm: 9.6.7
```

**Comment by mattinannt** [comment]
@bnmg thanks for raising this issue :-) 

@Dhruwang Do you have an idea how this might have happened and what the error message is telling us?
