### ISSUE TITLE
[BUG] SignUp with Keycloak OCID fails due to `refresh_expires_in`

### ISSUE THREAD

**Issue by gdnmhr** [formbricks/formbricks#2444]
### Issue Summary

When using Keycloak as IDP, all sign-ups will fail. Keycloak includes the attribute `refresh_expires_in` in its response which cannot be handled by Formbricks.

### Steps to Reproduce

1. Setup Formbricks with Keycloak as IDP
2. Sign-up as a new user

### Expected behavior

The user should be created and logged in.

### Other information

Log (tokens are redacted):

```
Invalid `prisma.account.create()` invocation:

{
  data: {
    provider: "openid",
    type: "oauth",
    providerAccountId: "provider_uuid",
    access_token: "some_access_token",
    expires_at: 1713036572,
    refresh_expires_in: 0,
    ~~~~~~~~~~~~~~~~~~
    token_type: "Bearer",
    id_token: "my_id_token",
    not-before-policy: 0,
    session_state: "some_state",
    scope: "openid email profile",
    userId: "some_id",
?   id?: String,
?   createdAt?: DateTime,
?   updatedAt?: DateTime,
?   refresh_token?: String | Null,
?   ext_expires_in?: Int | Null,
?   user?: UserCreateNestedOneWithoutAccountsInput
  }
}

Unknown argument `refresh_expires_in`. Available options are marked with ?." is an invalid header value.
    at webidl.errors.exception (node:internal/deps/undici/undici:1581:14)
    at webidl.errors.invalidArgument (node:internal/deps/undici/undici:1592:28)
    at _Headers.set (node:internal/deps/undici/undici:2173:31)
    at t.toResponse (/home/nextjs/apps/web/.next/server/chunks/7991.js:25:22019)
    at a (/home/nextjs/apps/web/.next/server/chunks/7991.js:25:19894)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e.length.t (/home/nextjs/apps/web/.next/server/chunks/7991.js:25:20998)
    at async /home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
```

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Ubuntu with latest Docker image v 1.6.1
```

**Comment by mattinannt** [comment]
@gdnmhr thanks for opening this issue. We will check what the best solution to this problem is :-) 

@ShubhamPalriwala Can you please try if you can reproduce the problem? Might just adding `refresh_expires_in` to the prisma schema might be a valid solution?

**Comment by ShubhamPalriwala** [comment]
Thanks for opening the issue! I was just able to reproduce the bug for signups due to the extra field as you suggested 👍🏼
