### ISSUE TITLE
[BUG] Survey answers filter not work

### ISSUE THREAD

**Issue by afcasasfranco** [formbricks/formbricks#2467]
### Filter not work and go to Error by role or not exist

I try to use the filter function.

<img width="1393" alt="Screenshot 2024-04-17 at 10 33 33 PM" src="https://github.com/formbricks/formbricks/assets/46802957/64ec5eb2-da5a-43c6-afdc-cabcee198700">

And when try to to select Search option show me.

- Error loading resources
- This resource doesn't exist or you don't have the neccessary rights to access it.

<img width="809" alt="Screenshot 2024-04-17 at 10 35 33 PM" src="https://github.com/formbricks/formbricks/assets/46802957/42bf9a02-98b2-4b4f-8e59-135f34f71e58">

### Steps to Reproduce

1. Select any survey
2. Clicked on Filter
3. Clickedd on add filter +
4. Search... Box

### Expected behavior

Fix the error or give me a idea how can fix to help community

### Screenshots

<img width="1393" alt="Screenshot 2024-04-17 at 10 33 33 PM" src="https://github.com/formbricks/formbricks/assets/46802957/0678cd27-ac3f-4685-a47a-89eaf383ea73">
<img width="809" alt="Screenshot 2024-04-17 at 10 35 33 PM" src="https://github.com/formbricks/formbricks/assets/46802957/a82402f3-bc3d-45a9-b0e1-eb7ad7372ef9">

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Linux - Docker latest image
```

**Comment by mattinannt** [comment]
@afcasasfranco Since you are on self-hosted, can you please check the server logs and share the error message that is thrown? :-)

**Comment by afcasasfranco** [comment]
Hi @mattinannt 

This are the server logs.

`Failed to get teams, redirecting to create-first-team
Could not Email :: SMTP not configured :: You're invited to collaborate on Formbricks!
Error: Failed to find Server Action "ece5bd333cb7d92256b1dac98ef1c69ad7e837a6". This request might be from an older or newer deployment. Original error: Invariant: Couldn't find action module ID from module map.
    at ry (/home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:1666)
    at /home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7035
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at rm (/home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6350)
    at rq (/home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1255)
    at /home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:3935
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:16239)
    at /home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:3825
    at AsyncLocalStorage.run (node:async_hooks:346:14)
Error: Failed to find Server Action "ece5bd333cb7d92256b1dac98ef1c69ad7e837a6". This request might be from an older or newer deployment. Original error: Invariant: Couldn't find action module ID from module map.
    at ry (/home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:1666)
    at /home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7035
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at rm (/home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:6350)
    at rq (/home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1255)
    at /home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:3935
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:16239)
    at /home/nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:3825
    at AsyncLocalStorage.run (node:async_hooks:346:14)
Could not Email :: SMTP not configured :: You've got a new team member!
Error: Team not found
    at p (/home/nextjs/apps/web/.next/server/app/(app)/environments/[environmentId]/settings/members/page.js:21:10543)
Error: Team not found
    at L (/home/nextjs/apps/web/.next/server/app/(app)/environments/[environmentId]/settings/members/page.js:21:22049)
O [AuthorizationError]: Not authorized
    at y (/home/nextjs/apps/web/.next/server/chunks/1678.js:1:37272) {
  statusCode: 403
}

> @formbricks/database@0.1.0 db:migrate:deploy /home/nextjs/packages/database
> prisma migrate deploy

Prisma schema loaded from schema.prisma
Datasource "db": PostgreSQL database "formbricks", schema "public" at "192.168.50.250:5432"

70 migrations found in prisma/migrations


No pending migrations to apply.
   ▲ Next.js 14.1.3
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Ready in 77ms

> @formbricks/database@0.1.0 db:migrate:deploy /home/nextjs/packages/database
> prisma migrate deploy

Prisma schema loaded from schema.prisma
Datasource "db": PostgreSQL database "formbricks", schema "public" at "192.168.50.250:5432"

70 migrations found in prisma/migrations


No pending migrations to apply.
   ▲ Next.js 14.1.3
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Ready in 69ms`
 
 But when make a filter, in this moment, logs not show anything.
 
 Additional i send the console logs.

`TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at H (9822-0183831d87520c3b.js:1:9718)
    at T (9822-0183831d87520c3b.js:1:8717)
    at 9822-0183831d87520c3b.js:1:7489
    at 9822-0183831d87520c3b.js:1:16046
    at Map.forEach (<anonymous>)
    at 9822-0183831d87520c3b.js:1:16035
    at aI (1dd3208c-e5f8207d2ef6f0e0.js:1:72883)
    at aU (1dd3208c-e5f8207d2ef6f0e0.js:1:72943)
    at aV (1dd3208c-e5f8207d2ef6f0e0.js:1:73382)`

I appreciatte your help.

**Comment by jimmy0017** [comment]
This happened to me as well. But i don't have any server side error log.

I have the following as JS log:

```
9997-855a7025e8810cc0.js:1 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at H (9822-0183831d87520c3b.js:1:9718)
    at T (9822-0183831d87520c3b.js:1:8717)
    at 9822-0183831d87520c3b.js:1:7489
    at 9822-0183831d87520c3b.js:1:16046
    at Map.forEach (<anonymous>)
    at 9822-0183831d87520c3b.js:1:16035
    at aI (1dd3208c-e5f8207d2ef6f0e0.js:1:72883)
    at aU (1dd3208c-e5f8207d2ef6f0e0.js:1:72943)
    at aV (1dd3208c-e5f8207d2ef6f0e0.js:1:73382)
window.console.error	@	9997-855a7025e8810cc0.js:1
```

**Comment by mattinannt** [comment]
@gupta-piyush19 can you please take a look at this and check whats going on / if you can reproduce the issue?

@jimmy0017 @afcasasfranco we are also releasing a new version of Formbricks in the next few days. Maybe the issue was already solved in the latest main branch :-)

**Comment by gupta-piyush19** [comment]
Thanks, @afcasasfranco and @jimmy0017, for the issue and the required context.
We've already fixed this issue on the main branch. The error is because of the breaking changes recently introduced in the `cmdk` package(which is used by the shadcn's combobox dropdown); you'd be able to use it after the formbricks 2.0 release. I am unsure if there is any other quick fix for self-hosted users.
cc: @mattinannt 

Bugfix PR: https://github.com/formbricks/formbricks/pull/2249
Issue in cmdk-based combobox: https://github.com/shadcn-ui/ui/issues/2944
