### ISSUE TITLE
Window is Not Defined

### ISSUE THREAD

**Issue by gboxxx** [formbricks/formbricks#260]
Getting the same error as #215 with v0.11. No errors in console, users are registering in Formbricks (seems pretty delayed), but no surveys are displayed. Using Local Wordpress install with Formbricks at a domain with reverse proxy. 

Docker on Synology NAS - v20.10.3
Docker Compose - v2.1.1

Full error: 
```
ReferenceError: window is not defined
    at SetupInstructions (/home/nextjs/apps/web/.next/server/app/environments/[environmentId]/settings/setup/page.js:778:17)
    at renderWithHooks (/home/nextjs/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8385:16)
    at renderIndeterminateComponent (/home/nextjs/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8459:15)
    at renderElement (/home/nextjs/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8694:7)
    at renderLazyComponent (/home/nextjs/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8674:3)
    at renderElement (/home/nextjs/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8784:11)
    at renderNodeDestructiveImpl (/home/nextjs/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8862:11)
    at renderNodeDestructive (/home/nextjs/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8834:14)
    at renderNode (/home/nextjs/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9018:12)
    at renderChildrenArray (/home/nextjs/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8970:7)
```

**Comment by mattinannt** [comment]
@gboxxx sorry to hear about your problems running Formbricks. Just to make sure: The error you reported is happening within the Formbricks app on the Setup instructions page?
Do you see any issues in the javascript/debug console on the wordpress page? What version of the SDK are you using on the wordpress page?

**Comment by gboxxx** [comment]
That's from the Docker container; not using SDK. Should I be, cause I'm definitely not a developer! -_- 

No errors in Firefox & Chrome Debug Console.

**Comment by gboxxx** [comment]
SDK version 0.1.6

I've only tried` Page URL` actions with `contains`, `starts with`, and `ends with`. Haven't tried `Inner Text` or `CSS Selector` yet as that wouldn't be my use case.

**Comment by mattinannt** [comment]
Can you share the page you embedded Formbricks in so I can have a look and see if I can spot the issue?

**Comment by gboxxx** [comment]
Sent email.
