### ISSUE TITLE
[BUG] docker compose fail to build @formbricks/web#build

### ISSUE THREAD

**Issue by whoo** [formbricks/formbricks#2717]
### Issue Summary

Docker compose failed to build.

### Steps to Reproduce

* git clone https://github.com/formbricks/formbricks.git
* docker compose up

### Expected behavior

docker should fire up.

### Screenshots

```docker
[+] Building 294.6s (25/38)                                                                                     docker:default
 => [formbricks internal] load build definition from Dockerfile                                                           0.1s
 => => transferring dockerfile: 2.98kB                                                                                    0.0s
 => [formbricks internal] load metadata for docker.io/library/node:20-alpine                                              0.6s
 => [formbricks auth] library/node:pull token for registry-1.docker.io                                                    0.0s
 => [formbricks internal] load .dockerignore                                                                              0.1s
 => => transferring context: 406B                                                                                         0.0s
 => [formbricks internal] load build context                                                                              0.2s
 => => transferring context: 190.03kB                                                                                     0.1s
 => [formbricks base 1/1] FROM docker.io/library/node:20-alpine@sha256:928b24aaadbd47c1a7722c563b471195ce54788bf8230ce80  0.0s
 => CACHED [formbricks runner  1/15] RUN corepack enable                                                                  0.0s
 => CACHED [formbricks runner  2/15] RUN apk add --no-cache curl     && apk add --no-cache supercronic     && adduser --  0.0s
 => CACHED [formbricks runner  3/15] WORKDIR /home/nextjs                                                                 0.0s
 => CACHED [formbricks installer  2/12] RUN apk update && apk add --no-cache g++ cmake make gcc python3 openssl-dev jq    0.0s
 => CACHED [formbricks installer  3/12] WORKDIR /app                                                                      0.0s
 => CACHED [formbricks installer  4/12] COPY .gitignore .gitignore                                                        0.0s
 => CACHED [formbricks builder 1/6] RUN apk add --no-cache libc6-compat                                                   0.0s
 => CACHED [formbricks builder 2/6] RUN apk update                                                                        0.0s
 => CACHED [formbricks builder 3/6] WORKDIR /app                                                                          0.0s
 => CACHED [formbricks builder 4/6] RUN yarn global add turbo                                                             0.0s
 => CACHED [formbricks builder 5/6] COPY . .                                                                              0.0s
 => CACHED [formbricks builder 6/6] RUN turbo prune @formbricks/web --docker                                              0.0s
 => CACHED [formbricks installer  5/12] COPY --from=builder /app/out/json/ .                                              0.0s
 => CACHED [formbricks installer  6/12] COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml                      0.0s
 => CACHED [formbricks installer  7/12] RUN pnpm install                                                                  0.0s
 => CACHED [formbricks installer  8/12] COPY --from=builder /app/out/full/ .                                              0.0s
 => CACHED [formbricks installer  9/12] RUN touch /app/apps/web/.env                                                      0.0s
 => CACHED [formbricks installer 10/12] RUN pnpm post-install --filter=web...                                             0.0s
 => ERROR [formbricks installer 11/12] RUN pnpm turbo run build --filter=web...                                         293.2s
------
 > [formbricks installer 11/12] RUN pnpm turbo run build --filter=web...:
1.397 • Packages in scope: @formbricks/api, @formbricks/database, @formbricks/ee, @formbricks/email, @formbricks/js, @formbricks/js-core, @formbricks/lib, @formbricks/surveys, @formbricks/tailwind-config, @formbricks/tsconfig, @formbricks/types, @formbricks/ui, @formbricks/web, eslint-config-formbricks
1.397 • Running build in 14 packages
1.397 • Remote caching disabled
1.567 @formbricks/database:post-install: cache bypass, force executing edeeda9411a7194b
1.587 @formbricks/surveys:build: cache miss, executing d3dc1914baebdf61
1.589 @formbricks/api:build: cache miss, executing 2f4a56adea37f8ad
2.130 @formbricks/database:post-install:
2.130 @formbricks/database:post-install: > @formbricks/database@0.1.0 post-install /app/packages/database
2.130 @formbricks/database:post-install: > pnpm generate
2.130 @formbricks/database:post-install:
2.147 @formbricks/surveys:build:
2.147 @formbricks/surveys:build: > @formbricks/surveys@1.0.0 build /app/packages/surveys
2.147 @formbricks/surveys:build: > tsc && vite build
2.147 @formbricks/surveys:build:
2.150 @formbricks/api:build:
2.150 @formbricks/api:build: > @formbricks/api@1.7.0 build /app/packages/api
2.150 @formbricks/api:build: > tsc && vite build
2.150 @formbricks/api:build:
2.847 @formbricks/database:post-install:
2.847 @formbricks/database:post-install: > @formbricks/database@0.1.0 generate /app/packages/database
2.847 @formbricks/database:post-install: > prisma generate
2.847 @formbricks/database:post-install:
3.934 @formbricks/database:post-install: Prisma schema loaded from schema.prisma
10.21 @formbricks/database:post-install:
10.21 @formbricks/database:post-install: ✔ Generated Prisma Client (v5.14.0) to ./../../node_modules/@prisma/client in 687ms
10.21 @formbricks/database:post-install:
10.21 @formbricks/database:post-install: ✔ Generated Zod Schemas (0.5.4) to ./zod in 920ms
10.21 @formbricks/database:post-install:
10.21 @formbricks/database:post-install: ✔ Generated Prisma Json Types Generator (3.0.4) to ./ in 3.03s
10.21 @formbricks/database:post-install:
10.21 @formbricks/database:post-install: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
10.21 @formbricks/database:post-install: ```
10.21 @formbricks/database:post-install: import { PrismaClient } from '@prisma/client'
10.21 @formbricks/database:post-install: const prisma = new PrismaClient()
10.21 @formbricks/database:post-install: ```
10.21 @formbricks/database:post-install: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
10.21 @formbricks/database:post-install: ```
10.21 @formbricks/database:post-install: import { PrismaClient } from '@prisma/client/edge'
10.21 @formbricks/database:post-install: const prisma = new PrismaClient()
10.21 @formbricks/database:post-install: ```
10.21 @formbricks/database:post-install:
10.21 @formbricks/database:post-install: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
10.21 @formbricks/database:post-install:
10.21 @formbricks/database:post-install: ┌─────────────────────────────────────────────────────────────┐
10.21 @formbricks/database:post-install: │  Deploying your app to serverless or edge functions?        │
10.21 @formbricks/database:post-install: │  Try Prisma Accelerate for connection pooling and caching.  │
10.21 @formbricks/database:post-install: │  https://pris.ly/cli/--accelerate                           │
10.21 @formbricks/database:post-install: └─────────────────────────────────────────────────────────────┘
10.21 @formbricks/database:post-install:
10.77 @formbricks/api:build: vite v5.2.11 building for production...
16.02 @formbricks/surveys:build: vite v5.2.11 building for production...
18.08 @formbricks/api:build: transforming...
18.19 @formbricks/api:build: ✓ 10 modules transformed.
18.22 @formbricks/api:build: rendering chunks...
18.24 @formbricks/api:build:
18.24 @formbricks/api:build: [vite:dts] Start generate declaration files...
18.29 @formbricks/api:build: computing gzip size...
18.31 @formbricks/api:build: dist/index.js  6.02 kB │ gzip: 1.65 kB │ map: 19.45 kB
18.32 @formbricks/api:build: [vite:dts] Start rollup declaration files...
20.05 @formbricks/api:build: Analysis will use the bundled TypeScript version 5.4.2
27.51 @formbricks/api:build: [vite:dts] Declaration files built in 16540ms.
27.51 @formbricks/api:build:
27.74 @formbricks/api:build: dist/index.umd.cjs  3.64 kB │ gzip: 1.42 kB │ map: 19.69 kB
27.74 @formbricks/api:build: ✓ built in 16.94s
27.88 @formbricks/js-core:build: cache miss, executing 9dbec681b3b4918d
28.03 @formbricks/surveys:build: transforming...
28.46 @formbricks/js-core:build:
28.46 @formbricks/js-core:build: > @formbricks/js-core@1.0.0 build /app/packages/js-core
28.46 @formbricks/js-core:build: > pnpm build:app && pnpm build:website
28.46 @formbricks/js-core:build:
28.99 @formbricks/surveys:build: src/components/wrappers/StackedCardsContainer.tsx (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
29.06 @formbricks/js-core:build:
29.06 @formbricks/js-core:build: > @formbricks/js-core@1.0.0 build:app /app/packages/js-core
29.06 @formbricks/js-core:build: > tsc && vite build --config app.vite.config.ts
29.06 @formbricks/js-core:build:
31.74 @formbricks/surveys:build: ✓ 139 modules transformed.
32.00 @formbricks/surveys:build: rendering chunks...
32.01 @formbricks/surveys:build:
32.01 @formbricks/surveys:build: [vite:dts] Start generate declaration files...
32.08 @formbricks/surveys:build: computing gzip size...
32.12 @formbricks/surveys:build: dist/style.css    1.99 kB │ gzip:   0.67 kB
32.12 @formbricks/surveys:build: dist/index.js   568.92 kB │ gzip: 109.54 kB
32.16 @formbricks/surveys:build: [vite:dts] Start rollup declaration files...
34.02 @formbricks/surveys:build: Analysis will use the bundled TypeScript version 5.4.2
37.73 @formbricks/js-core:build: vite v5.2.11 building for production...
41.21 @formbricks/surveys:build: [vite:dts] Declaration files built in 21311ms.
41.21 @formbricks/surveys:build:
44.57 @formbricks/surveys:build: dist/style.css        1.99 kB │ gzip:  0.67 kB
44.57 @formbricks/surveys:build: dist/index.umd.cjs  307.54 kB │ gzip: 81.68 kB
44.57 @formbricks/surveys:build: ✓ built in 28.52s
48.69 @formbricks/js-core:build: transforming...
49.01 @formbricks/js-core:build: ✓ 30 modules transformed.
49.60 @formbricks/js-core:build: rendering chunks...
49.63 @formbricks/js-core:build:
49.63 @formbricks/js-core:build: [vite:dts] Start generate declaration files...
49.69 @formbricks/js-core:build: computing gzip size...
49.70 @formbricks/js-core:build: dist/app.umd.cjs  26.00 kB │ gzip: 8.04 kB │ map: 113.74 kB
49.72 @formbricks/js-core:build: [vite:dts] Start rollup declaration files...
51.32 @formbricks/js-core:build: Analysis will use the bundled TypeScript version 5.4.2
57.77 @formbricks/js-core:build: [vite:dts] Declaration files built in 19089ms.
57.77 @formbricks/js-core:build:
57.77 @formbricks/js-core:build: ✓ built in 20.00s
58.51 @formbricks/js-core:build:
58.51 @formbricks/js-core:build: > @formbricks/js-core@1.0.0 build:website /app/packages/js-core
58.51 @formbricks/js-core:build: > tsc && vite build --config website.vite.config.ts
58.51 @formbricks/js-core:build:
65.60 @formbricks/js-core:build: vite v5.2.11 building for production...
75.45 @formbricks/js-core:build: transforming...
75.79 @formbricks/js-core:build: ✓ 29 modules transformed.
76.36 @formbricks/js-core:build: rendering chunks...
76.39 @formbricks/js-core:build:
76.39 @formbricks/js-core:build: [vite:dts] Start generate declaration files...
76.46 @formbricks/js-core:build: computing gzip size...
76.47 @formbricks/js-core:build: dist/website.umd.cjs  23.35 kB │ gzip: 7.46 kB │ map: 108.49 kB
76.48 @formbricks/js-core:build: [vite:dts] Start rollup declaration files...
77.86 @formbricks/js-core:build: Analysis will use the bundled TypeScript version 5.4.2
84.50 @formbricks/js-core:build: [vite:dts] Declaration files built in 17954ms.
84.50 @formbricks/js-core:build:
84.50 @formbricks/js-core:build: ✓ built in 18.86s
84.66 @formbricks/js:build: cache miss, executing 3509df0cc11e824c
85.20 @formbricks/js:build:
85.20 @formbricks/js:build: > @formbricks/js@2.0.1 build /app/packages/js
85.20 @formbricks/js:build: > tsc && vite build
85.20 @formbricks/js:build:
88.77 @formbricks/js:build: vite v5.2.11 building for production...
91.42 @formbricks/js:build: transforming...
91.48 @formbricks/js:build: ✓ 5 modules transformed.
91.50 @formbricks/js:build: rendering chunks...
91.51 @formbricks/js:build:
91.51 @formbricks/js:build: [vite:dts] Start generate declaration files...
91.56 @formbricks/js:build: computing gzip size...
91.57 @formbricks/js:build: dist/app.js                      0.35 kB │ gzip: 0.23 kB │ map:  0.90 kB
91.57 @formbricks/js:build: dist/website.js                  0.37 kB │ gzip: 0.23 kB │ map:  0.93 kB
91.57 @formbricks/js:build: dist/loadFormbricks-BzaImH2L.js  3.94 kB │ gzip: 1.19 kB │ map: 12.31 kB
91.58 @formbricks/js:build: [vite:dts] Start rollup declaration files...
92.99 @formbricks/js:build: Analysis will use the bundled TypeScript version 5.4.2
99.74 @formbricks/js:build: Analysis will use the bundled TypeScript version 5.4.2
107.8 @formbricks/js:build: [vite:dts] Declaration files built in 18889ms.
107.8 @formbricks/js:build:
108.2 @formbricks/js:build: dist/app.cjs                      0.19 kB │ gzip: 0.17 kB │ map:  0.94 kB
108.2 @formbricks/js:build: dist/website.cjs                  0.20 kB │ gzip: 0.18 kB │ map:  0.97 kB
108.2 @formbricks/js:build: dist/loadFormbricks-CdxDGQiG.cjs  2.05 kB │ gzip: 0.89 kB │ map: 12.19 kB
108.2 @formbricks/js:build: ✓ built in 19.41s
108.4 @formbricks/web:build: cache miss, executing 410e57bcc4f9f05b
109.3 @formbricks/web:build:
109.3 @formbricks/web:build: > @formbricks/web@2.0.3 build /app/apps/web
109.3 @formbricks/web:build: > next build
109.3 @formbricks/web:build:
111.8 @formbricks/web:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
111.8 @formbricks/web:build: This information is used to shape Next.js' roadmap and prioritize features.
111.8 @formbricks/web:build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
111.8 @formbricks/web:build: https://nextjs.org/telemetry
111.8 @formbricks/web:build:
111.9 @formbricks/web:build:   ▲ Next.js 15.0.0-rc.0
111.9 @formbricks/web:build:   - Environments: .env
111.9 @formbricks/web:build:
112.2 @formbricks/web:build:    Creating an optimized production build ...
202.9 @formbricks/web:build:  ⚠ Compiled with warnings
202.9 @formbricks/web:build:
202.9 @formbricks/web:build: ../../node_modules/next/dist/compiled/react/cjs/react.react-server.production.js
202.9 @formbricks/web:build: A Node.js API is used (process.emit at line: 289) which is not supported in the Edge Runtime.
202.9 @formbricks/web:build: Learn more: https://nextjs.org/docs/api-reference/edge-runtime
202.9 @formbricks/web:build:
202.9 @formbricks/web:build: Import trace for requested module:
202.9 @formbricks/web:build: ../../node_modules/next/dist/compiled/react/cjs/react.react-server.production.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/compiled/react/react.react-server.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/server/app-render/dynamic-rendering.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/server/after/after.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/server/after/index.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/server/web/exports/index.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/api/server.js
202.9 @formbricks/web:build:
202.9 @formbricks/web:build: ../../node_modules/next/dist/compiled/react/cjs/react.react-server.production.js
202.9 @formbricks/web:build: A Node.js API is used (process.emit at line: 291) which is not supported in the Edge Runtime.
202.9 @formbricks/web:build: Learn more: https://nextjs.org/docs/api-reference/edge-runtime
202.9 @formbricks/web:build:
202.9 @formbricks/web:build: Import trace for requested module:
202.9 @formbricks/web:build: ../../node_modules/next/dist/compiled/react/cjs/react.react-server.production.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/compiled/react/react.react-server.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/server/app-render/dynamic-rendering.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/server/after/after.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/server/after/index.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/server/web/exports/index.js
202.9 @formbricks/web:build: ../../node_modules/next/dist/esm/api/server.js
202.9 @formbricks/web:build:
227.5 @formbricks/web:build:  ✓ Compiled successfully
227.5 @formbricks/web:build:    Linting and checking validity of types ...
283.4 @formbricks/web:build:    Collecting page data ...
286.4 @formbricks/web:build:  ⚠ Using edge runtime on a page currently disables static generation for that page
287.5 @formbricks/web:build:    Generating static pages (0/55) ...
292.0 @formbricks/web:build: TypeError: Cannot read properties of null (reading 'useContext')
292.0 @formbricks/web:build:     at exports.useContext (/app/apps/web/node_modules/react/cjs/react.production.js:489:33)
292.0 @formbricks/web:build:     at h (/app/apps/web/.next/server/pages/_error.js:1:6021)
292.0 @formbricks/web:build:     at renderWithHooks (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3927:18)
292.0 @formbricks/web:build:     at renderElement (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4086:17)
292.0 @formbricks/web:build:     at renderNodeDestructive (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
292.0 @formbricks/web:build:     at renderNode (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4841:14)
292.0 @formbricks/web:build:     at renderChildrenArray (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4773:7)
292.0 @formbricks/web:build:     at renderNodeDestructive (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4630:9)
292.0 @formbricks/web:build:     at renderNode (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4841:14)
292.0 @formbricks/web:build:     at renderElement (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4127:7)
292.0 @formbricks/web:build:
292.0 @formbricks/web:build: Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
292.0 @formbricks/web:build:
292.0 @formbricks/web:build: TypeError: Cannot read properties of null (reading 'useContext')
292.0 @formbricks/web:build:     at exports.useContext (/app/apps/web/node_modules/react/cjs/react.production.js:489:33)
292.0 @formbricks/web:build:     at h (/app/apps/web/.next/server/pages/_error.js:1:6021)
292.0 @formbricks/web:build:     at renderWithHooks (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3927:18)
292.0 @formbricks/web:build:     at renderElement (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4086:17)
292.0 @formbricks/web:build:     at renderNodeDestructive (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
292.0 @formbricks/web:build:     at renderNode (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4841:14)
292.0 @formbricks/web:build:     at renderChildrenArray (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4773:7)
292.0 @formbricks/web:build:     at renderNodeDestructive (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4630:9)
292.0 @formbricks/web:build:     at renderNode (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4841:14)
292.0 @formbricks/web:build:     at renderElement (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4127:7)
292.0 @formbricks/web:build: TypeError: Cannot read properties of null (reading 'useContext')
292.0 @formbricks/web:build:     at exports.useContext (/app/apps/web/node_modules/react/cjs/react.production.js:489:33)
292.0 @formbricks/web:build:     at h (/app/apps/web/.next/server/pages/_error.js:1:6021)
292.0 @formbricks/web:build:     at renderWithHooks (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3927:18)
292.0 @formbricks/web:build:     at renderElement (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4086:17)
292.0 @formbricks/web:build:     at renderNodeDestructive (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
292.0 @formbricks/web:build:     at renderNode (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4841:14)
292.0 @formbricks/web:build:     at renderChildrenArray (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4773:7)
292.0 @formbricks/web:build:     at renderNodeDestructive (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4630:9)
292.0 @formbricks/web:build:     at renderNode (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4841:14)
292.0 @formbricks/web:build:     at renderElement (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4127:7)
292.0 @formbricks/web:build:
292.0 @formbricks/web:build: Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
292.0 @formbricks/web:build:
292.0 @formbricks/web:build: TypeError: Cannot read properties of null (reading 'useContext')
292.0 @formbricks/web:build:     at exports.useContext (/app/apps/web/node_modules/react/cjs/react.production.js:489:33)
292.0 @formbricks/web:build:     at h (/app/apps/web/.next/server/pages/_error.js:1:6021)
292.0 @formbricks/web:build:     at renderWithHooks (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3927:18)
292.0 @formbricks/web:build:     at renderElement (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4086:17)
292.0 @formbricks/web:build:     at renderNodeDestructive (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
292.0 @formbricks/web:build:     at renderNode (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4841:14)
292.0 @formbricks/web:build:     at renderChildrenArray (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4773:7)
292.0 @formbricks/web:build:     at renderNodeDestructive (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4630:9)
292.0 @formbricks/web:build:     at renderNode (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4841:14)
292.0 @formbricks/web:build:     at renderElement (/app/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4127:7)
292.1 @formbricks/web:build:
292.1 @formbricks/web:build: > Build error occurred
292.1 @formbricks/web:build: Error: Export encountered an error on /500, exiting due to prerenderEarlyExit: true being set
292.1 @formbricks/web:build:     at /app/node_modules/next/dist/export/index.js:481:23
292.1 @formbricks/web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
292.1 @formbricks/web:build:     at async Promise.all (index 1)
292.1 @formbricks/web:build:     at async exportAppImpl (/app/node_modules/next/dist/export/index.js:442:21)
292.1 @formbricks/web:build:     at async /app/node_modules/next/dist/export/index.js:625:16
292.1 @formbricks/web:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:157:20)
292.1 @formbricks/web:build:     at async /app/node_modules/next/dist/build/index.js:1690:42
292.1 @formbricks/web:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:157:20)
292.1 @formbricks/web:build:     at async /app/node_modules/next/dist/build/index.js:1548:17
292.1 @formbricks/web:build:     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:157:20)
292.1 @formbricks/web:build:     at async build (/app/node_modules/next/dist/build/index.js:372:9)
292.2 @formbricks/web:build:  ELIFECYCLE  Command failed with exit code 1.
292.2 @formbricks/web:build: ERROR: command finished with error: command (/app/apps/web) /usr/local/bin/pnpm run build exited (1)
292.2 @formbricks/web#build: command (/app/apps/web) /usr/local/bin/pnpm run build exited (1)
292.2
292.2  Tasks:    5 successful, 6 total
292.2 Cached:    0 cached, 6 total
292.2   Time:    4m50.871s
292.2 Failed:    @formbricks/web#build
292.2
292.2  ERROR  run failed: command  exited (1)
------
failed to solve: process "/bin/sh -c pnpm turbo run build --filter=web..." did not complete successfully: exit code: 1
```

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: [Docker]
- Node: [Docker]
- npm:  [docker]
```

**Comment by mattinannt** [comment]
@whoo thanks for raising an issue 😊
Can you please share more about the operating system of the machine where you are trying to build the image.

What's your use case of building the image yourself and not using the pre-built images?

**Comment by mmopinodo** [comment]
```
~/WebstormProjects/formbricks git:[main]
docker-compose up

[+] Building 3.4s (23/37)                                                                                                                                                                 docker:desktop-linux
 => [formbricks internal] load build definition from Dockerfile                                                                                                                                           0.0s
 => => transferring dockerfile: 2.98kB                                                                                                                                                                    0.0s
 => [formbricks internal] load metadata for docker.io/library/node:20-alpine                                                                                                                              0.5s
 => [formbricks internal] load .dockerignore                                                                                                                                                              0.0s
 => => transferring context: 406B                                                                                                                                                                         0.0s
 => [formbricks base 1/1] FROM docker.io/library/node:20-alpine@sha256:66c7d989b6dabba6b4305b88f40912679aebd9f387a5b16ffa76dfb9ae90b060                                                                   0.0s
 => [formbricks internal] load build context                                                                                                                                                              1.4s
 => => transferring context: 277.05MB                                                                                                                                                                     1.4s
 => CACHED [formbricks runner  1/15] RUN corepack enable                                                                                                                                                  0.0s
 => CACHED [formbricks runner  2/15] RUN apk add --no-cache curl     && apk add --no-cache supercronic     && adduser --system --uid 1001 nextjs                                                          0.0s
 => CACHED [formbricks runner  3/15] WORKDIR /home/nextjs                                                                                                                                                 0.0s
 => CACHED [formbricks builder 1/6] RUN apk add --no-cache libc6-compat                                                                                                                                   0.0s
 => CACHED [formbricks builder 2/6] RUN apk update                                                                                                                                                        0.0s
 => CACHED [formbricks builder 3/6] WORKDIR /app                                                                                                                                                          0.0s
 => CACHED [formbricks builder 4/6] RUN yarn global add turbo                                                                                                                                             0.0s
 => [formbricks builder 5/6] COPY . .                                                                                                                                                                     0.4s
 => [formbricks builder 6/6] RUN turbo prune @formbricks/web --docker                                                                                                                                     0.6s
 => CACHED [formbricks installer  2/12] RUN apk update && apk add --no-cache g++ cmake make gcc python3 openssl-dev jq                                                                                    0.0s
 => CACHED [formbricks installer  3/12] WORKDIR /app                                                                                                                                                      0.0s
 => CACHED [formbricks installer  4/12] COPY .gitignore .gitignore                                                                                                                                        0.0s
 => CACHED [formbricks installer  5/12] COPY --from=builder /app/out/json/ .                                                                                                                              0.0s
 => CACHED [formbricks installer  6/12] COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml                                                                                                      0.0s
 => CACHED [formbricks installer  7/12] RUN pnpm install                                                                                                                                                  0.0s
 => CACHED [formbricks installer  8/12] COPY --from=builder /app/out/full/ .                                                                                                                              0.0s
 => CACHED [formbricks installer  9/12] RUN touch /app/apps/web/.env                                                                                                                                      0.0s
 => ERROR [formbricks installer 10/12] RUN pnpm post-install --filter=web...                                                                                                                              0.3s
 > [formbricks installer 10/12] RUN pnpm post-install --filter=web...:
0.259
0.259 > formbricks@0.0.0 post-install /app
0.259 > turbo run post-install "--filter=web..."
0.259
0.278
0.278 Attention:
0.278 Turborepo now collects completely anonymous telemetry regarding usage.
0.278 This information is used to shape the Turborepo roadmap and prioritize features.
0.278 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
0.278 https://turbo.build/repo/docs/telemetry
0.278
0.321   x missing tasks in project
0.321
0.321 Error:   x could not find task `post-install` in project
0.321
0.324  ELIFECYCLE  Command failed with exit code 1.
------
failed to solve: process "/bin/sh -c pnpm post-install --filter=web..." did not complete successfully: exit code: 1
```

I also just checked out the repository and ran `docker-compose up` 

Similar thing happens if I run `docker build -f ./apps/web/Dockerfile .` :

```

[+] Building 0.9s (23/37)                                                                            docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                 0.0s
 => => transferring dockerfile: 2.98kB                                                                               0.0s
 => [internal] load metadata for docker.io/library/node:20-alpine                                                    0.5s
 => [internal] load .dockerignore                                                                                    0.0s
 => => transferring context: 406B                                                                                    0.0s
 => [base 1/1] FROM docker.io/library/node:20-alpine@sha256:66c7d989b6dabba6b4305b88f40912679aebd9f387a5b16ffa76dfb  0.0s
 => [internal] load build context                                                                                    0.1s
 => => transferring context: 192.91kB                                                                                0.1s
 => CACHED [runner  1/15] RUN corepack enable                                                                        0.0s
 => CACHED [runner  2/15] RUN apk add --no-cache curl     && apk add --no-cache supercronic     && adduser --system  0.0s
 => CACHED [runner  3/15] WORKDIR /home/nextjs                                                                       0.0s
 => CACHED [installer  2/12] RUN apk update && apk add --no-cache g++ cmake make gcc python3 openssl-dev jq          0.0s
 => CACHED [installer  3/12] WORKDIR /app                                                                            0.0s
 => CACHED [installer  4/12] COPY .gitignore .gitignore                                                              0.0s
 => CACHED [builder 1/6] RUN apk add --no-cache libc6-compat                                                         0.0s
 => CACHED [builder 2/6] RUN apk update                                                                              0.0s
 => CACHED [builder 3/6] WORKDIR /app                                                                                0.0s
 => CACHED [builder 4/6] RUN yarn global add turbo                                                                   0.0s
 => CACHED [builder 5/6] COPY . .                                                                                    0.0s
 => CACHED [builder 6/6] RUN turbo prune @formbricks/web --docker                                                    0.0s
 => CACHED [installer  5/12] COPY --from=builder /app/out/json/ .                                                    0.0s
 => CACHED [installer  6/12] COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml                            0.0s
 => CACHED [installer  7/12] RUN pnpm install                                                                        0.0s
 => CACHED [installer  8/12] COPY --from=builder /app/out/full/ .                                                    0.0s
 => CACHED [installer  9/12] RUN touch /app/apps/web/.env                                                            0.0s
 => ERROR [installer 10/12] RUN pnpm post-install --filter=web...                                                    0.3s
------
 > [installer 10/12] RUN pnpm post-install --filter=web...:
0.242
0.242 > formbricks@0.0.0 post-install /app
0.242 > turbo run post-install "--filter=web..."
0.242
0.260
0.260 Attention:
0.260 Turborepo now collects completely anonymous telemetry regarding usage.
0.260 This information is used to shape the Turborepo roadmap and prioritize features.
0.260 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
0.260 https://turbo.build/repo/docs/telemetry
0.260
0.302   x missing tasks in project
0.302
0.302 Error:   x could not find task `post-install` in project
0.302
0.305  ELIFECYCLE  Command failed with exit code 1.
------
Dockerfile:51
--------------------
  49 |
  50 |     # Build the project
  51 | >>> RUN pnpm post-install --filter=web...
  52 |     RUN pnpm turbo run build --filter=web...
  53 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm post-install --filter=web..." did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/hng6pz4mamgzr9ntuhps5jr4o
```

I am running this on an m3 MacBook ARM processor.

**Comment by mattinannt** [comment]
A lot of these errors has been fixed 😊
If you face new issues with the current version of the Dockerfile, please open a new bug ticket.

**Comment by hassansaadat** [comment]
> A lot of these errors has been fixed 😊 If you face new issues with the current version of the Dockerfile, please open a new bug ticket.

Hi,  
I’ve encountered the exactly same issues, and they remain unresolved. The Dockerfile hasn’t been updated in the past three months, and it still contains some poorly commented lines.
Could you please address this?  
Thanks!
