### ISSUE TITLE
[BUG] - Unable to change or delete Avatar

### ISSUE THREAD

**Issue by pierrejo** [formbricks/formbricks#2766]
### Issue Summary

I make all migration and upload image in form is working

LOG :

```bash
No pending migrations to apply.
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
npm notice To update run: npm install -g npm@10.8.1
npm notice
  ▲ Next.js 15.0.0-rc.0
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 180ms


Error: Deletion failed: Deletion failed
    at U (/home/nextjs/apps/web/.next/server/app/(app)/environments/[environmentId]/settings/(account)/profile/page.js:11:13636)
    at async /home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:128:1202
    at async r$ (/home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:127:8130)
    at async nn (/home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:129:1140)
    at async doRender (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:1490:34)
    at async responseGenerator (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:1652:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:1665:28)
    at async NextNodeServer.renderPageComponent (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:1978:24)
    at async NextNodeServer.renderToResponseImpl (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:2016:32)
    at async NextNodeServer.pipeImpl (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:908:25) {
  digest: '1690535866'
}
```

### Steps to Reproduce

Just try to change or delete Avatar image

### Expected behavior

change or delete Avatar image with success

### Screenshots

![2024-06-13_13-04](https://github.com/formbricks/formbricks/assets/48883970/eb9b4a48-4ee9-4e87-b155-ec7fd1a9c159)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

**Comment by edersilva78** [comment]
Hi, Team
Also encoutered this issue

```
formbricks-formbricks-1 |  ⨯ upstream image response failed for https://forms.institutomix.com.br/storage/cllw9vnu60003o03dwu5kufcc/public/IMG_2640--fid--2a21d49f-8780-4211-a4cf-65a67a44a687.JPG 404
formbricks-formbricks-1 | Error: Deletion failed: Deletion failed
formbricks-formbricks-1 |     at U (/home/nextjs/apps/web/.next/server/app/(app)/environments/[environmentId]/settings/(account)/profile/page.js:11:13636)
formbricks-formbricks-1 |     at async /home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:128:1202
formbricks-formbricks-1 |     at async r$ (/home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:127:8130)
formbricks-formbricks-1 |     at async nn (/home/nextjs/apps/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:129:1140)
formbricks-formbricks-1 |     at async doRender (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:1490:34)
formbricks-formbricks-1 |     at async responseGenerator (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:1652:28)
formbricks-formbricks-1 |     at async NextNodeServer.renderToResponseWithComponentsImpl (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:1665:28)
formbricks-formbricks-1 |     at async NextNodeServer.renderPageComponent (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:1978:24)
formbricks-formbricks-1 |     at async NextNodeServer.renderToResponseImpl (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:2016:32)
formbricks-formbricks-1 |     at async NextNodeServer.pipeImpl (/home/nextjs/apps/web/node_modules/next/dist/server/base-server.js:908:25) {
formbricks-formbricks-1 |   digest: '1690535866'
formbricks-formbricks-1 | }
```

**Comment by mattinannt** [comment]
@Dhruwang Can you please look into this and see if you can reproduce and solve the issue? :-)

**Comment by smritidoneria** [comment]
I am encountering an issue where the avatar deletion and update functionalities work perfectly in the local environment but fail to operate as expected on Formbricks Cloud.

**Comment by ag-gaphp** [comment]
@edersilva78 & @pierrejo If you're able to check, what are the permissions on your uploads directory? This could be related to #2694

**Comment by edersilva78** [comment]
Hi, @ag-gaphp 

Thanks for your repply.

The error persists after appending  the :rw to volume
![image](https://github.com/user-attachments/assets/d301a3c4-671d-4f3d-82f9-b6a66321c1c0)


![image](https://github.com/user-attachments/assets/45ab7e65-e7a5-4541-90e9-70ee061b3f1d)

**Comment by pierrejo** [comment]
> @edersilva78 & @pierrejo If you're able to check, what are the permissions on your uploads directory? This could be related to #2694

Thanks for your reply. 

Despite changing file and folder permissions, nothing changes on my end (I also tried: `chmod -R 777`)

**Comment by edersilva78** [comment]
Hi! @pierrejo 

I managed to fix the issue by updating the database records manually.

 `update "Product" set logo = '{}'::jsonb;`

`update "User" set imageURL = NULL`

**Comment by jobenjada** [comment]
@Dhruwang whats the status here? Pls follow up or update the ticket status

**Comment by edersilva78** [comment]
it's working for me now. my problems was related to a (missing/not applied) migration

**Comment by mattinannt** [comment]
@pierrejo Are you still facing this issue with the latest version?
