### ISSUE TITLE
[BUG] Unknown argument `response`. Did you mean `responseId`?

### ISSUE THREAD

**Issue by Jaarson** [formbricks/formbricks#3035]
### Issue Summary

I use self-hosted Formbricks via Docker.
There are a bunch of errors as users fill out the Link Survey (for each answer submitted). However, data is saved and I can see the responses. Additionally, email notifications are not being sent. I have set up the app's `SMTP_...` environment variables.

### Steps to Reproduce

1. Self-host with docker
2. Create Link survey
3. Open link and start filling it out

### Expected behavior

no errors, email notifications are being sent

### Other information

```
PrismaClientValidationError: 
Invalid `prisma.display.update()` invocation:
{
  where: {
    id: "cm03i124300027xrx3vwc2sd4"
  },
  data: {
    response: {
    ~~~~~~~~
      connect: {
        id: "cm03i155t00037xrx2wq39sdk"
      }
    },
?   id?: String | StringFieldUpdateOperationsInput,
?   createdAt?: DateTime | DateTimeFieldUpdateOperationsInput,
?   updatedAt?: DateTime | DateTimeFieldUpdateOperationsInput,
?   responseId?: String | NullableStringFieldUpdateOperationsInput | Null,
?   status?: DisplayStatus | NullableEnumDisplayStatusFieldUpdateOperationsInput | Null,
?   survey?: SurveyUpdateOneRequiredWithoutDisplaysNestedInput,
?   person?: PersonUpdateOneWithoutDisplaysNestedInput
  },
  select: {
    id: true,
    createdAt: true,
    updatedAt: true,
    surveyId: true,
    responseId: true,
    personId: true,
    status: true
  }
}
Unknown argument `response`. Did you mean `responseId`? Available options are marked with ?.
    at An (/home/nextjs/node_modules/@prisma/client/runtime/library.js:114:7526)
    at _n.handleRequestError (/home/nextjs/node_modules/@prisma/client/runtime/library.js:121:7392)
    at _n.handleAndLogRequestError (/home/nextjs/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/home/nextjs/node_modules/@prisma/client/runtime/library.js:121:6741)
    at async l (/home/nextjs/node_modules/@prisma/client/runtime/library.js:130:9355)
    at async p (/home/nextjs/apps/web/.next/server/chunks/8215.js:1:16736)
    at async p (/home/nextjs/apps/web/.next/server/app/api/v1/client/[environmentId]/displays/[displayId]/route.js:1:1082)
    at async /home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
    at async eR.execute (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
    at async eR.handle (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512) {
  clientVersion: '5.18.0'
}
Error sending event to pipeline: TypeError: fetch failed
```

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Docker (macOS)
- Node: v20.16.0
- npm: 10.8.1
```

**Comment by mattinannt** [comment]
@Jaarson thanks for raising an issue. We were able to reproduce the issue and pushed a fix in https://github.com/formbricks/formbricks/pull/3034 .
We will release a new self-hosting release soon that includes the fix :-)

**Comment by Jaarson** [comment]
Thank you! 🫶

**Comment by Jaarson** [comment]
@mattinannt is it safe to send surveys to people now, or should I wait for the release?
