### ISSUE TITLE
[BUG] ReferenceError: firstEnabledEnding is not defined

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3044]
### Issue Summary

It seems like one of our surveys is somehow misconfigured and causes the following error on each survey sync:

```
ReferenceError: firstEnabledEnding is not defined
    at o (/home/nextjs/apps/web/.next/server/chunks/8215.js:1:47212)
    at u (/home/nextjs/apps/web/.next/server/chunks/8215.js:1:48037)
    at /home/nextjs/apps/web/.next/server/app/api/v1/client/[environmentId]/website/sync/route.js:1:2912
    at Array.map (<anonymous>)
    at y (/home/nextjs/apps/web/.next/server/app/api/v1/client/[environmentId]/website/sync/route.js:1:2897)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
    at async eR.execute (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
    at async eR.handle (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512)
    at async doRender (/home/nextjs/node_modules/next/dist/server/base-server.js:1377:42)
```

I've run all migrations and restarted Redis.

### Steps to Reproduce

1. Error is thrown on every survey sync, unfortunately the error message is too unspecific which makes it hard to find the misconfigured survey

### Expected behavior

no error on survey sync :)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.4.3
```

**Comment by mattinannt** [comment]
@Dhruwang Can you please check if you can reproduce the issue? Flix is self-hosting Formbricks and is using website surveys.

**Comment by Dhruwang** [comment]
Hey @jonas-hoebenreich , can you confirm, which version of Formbricks are you using ? 😊

i investigated this issue and found out a problem in `packages/lib/i18n` in `reverseTranslateSurvey` function. So basically this function is used to transform surveys with `i18n` strings to survey with normal string. But this only runs for the older versions of Formbricks 🤔

**Comment by jonas-hoebenreich** [comment]
We are using v2.4.3 in the backend and the issue happened when trying to sync with an outdated version "/website/sync?version=1.6.5"

**Comment by Dhruwang** [comment]
Hey @jonas-hoebenreich, in order to fix that, you will need to update version from 1.6.5 to something greater than 2.0.0 which does not call reverse translate function 😊🙌🏻
