### ISSUE TITLE
[BUG] Airtable integration not working

### ISSUE THREAD

**Issue by domibarton** [formbricks/formbricks#3994]
### Issue Summary

The Airtable integration on a self-hosted instance doesn't work. The redirect works, but then Formbricks returns a HTTP 500 error, and on the console I see this:

```
Error: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "access_token"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "refresh_token"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "nan",
    "path": [
      "expires_in"
    ],
    "message": "Expected number, received nan"
  }
]
    at u (/home/nextjs/apps/web/.next/server/app/(app)/environments/[environmentId]/integrations/airtable/page.js:1:21848)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async b (/home/nextjs/apps/web/.next/server/app/api/v1/integrations/airtable/callback/route.js:1:2268)
    at async /home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36957
    at async eC.execute (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27552)
    at async eC.handle (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38291)
    at async doRender (/home/nextjs/node_modules/next/dist/server/base-server.js:1352:42)
    at async cacheEntry.responseCache.get.routeKind (/home/nextjs/node_modules/next/dist/server/base-server.js:1574:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/home/nextjs/node_modules/next/dist/server/base-server.js:1482:28)
    at async NextNodeServer.renderPageComponent (/home/nextjs/node_modules/next/dist/server/base-server.js:1908:24)
 ⨯ Error: No response is returned from route handler '/app/apps/web/app/api/v1/integrations/airtable/callback/route.ts'. Ensure you return a `Response` or a `NextResponse` in all branches of your handler.
    at /home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37122
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eC.execute (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27552)
    at async eC.handle (/home/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38291)
    at async doRender (/home/nextjs/node_modules/next/dist/server/base-server.js:1352:42)
    at async cacheEntry.responseCache.get.routeKind (/home/nextjs/node_modules/next/dist/server/base-server.js:1574:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/home/nextjs/node_modules/next/dist/server/base-server.js:1482:28)
    at async NextNodeServer.renderPageComponent (/home/nextjs/node_modules/next/dist/server/base-server.js:1908:24)
    at async NextNodeServer.renderToResponseImpl (/home/nextjs/node_modules/next/dist/server/base-server.js:1946:32)
    at async NextNodeServer.pipeImpl (/home/nextjs/node_modules/next/dist/server/base-server.js:921:25)
```

### Steps to Reproduce

1. Go to the official docs for the [airtable integration](https://formbricks.com/docs/self-hosting/integrations#airtable)
2. Follow the self-hosted steps
3. Copy the client ID and define it as `AIRTABLE_CLIENT_ID` environment variable
4. Redeploy Formbricks
5. Click on the "Connect" button on the Airtable integration (which was greyed-out until we reconfigured the `AIRTABLE_CLIENT_ID` variable)
6. Select base and click on "Grant access" on Airtable

### Expected behavior

1. Browser redirects back to Formbricks
2. Formbricks activates the integration

### Other information

The `AIRTABLE_REDIRECT_URL` is not used in the code, thus it's not required.  
As guessed, the redirect URL is automatically built [here](apps/web/app/api/v1/integrations/airtable/callback/route.ts#L47).

The docs should be updated, I'll try to do that in a dedicated PR.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
Official `ghcr.io/formbricks/formbricks:v2.5.3` image.  
Also tried `ghcr.io/formbricks/formbricks:v2.6.0.` (and applied migrations) with the same result.
```

**Comment by jobenjada** [comment]
thanks a lot for flagging this! :) we'll look into it and get back to you

**Comment by Dhruwang** [comment]
Hey @domibarton , thanks for reposting this issue. The problem that you face here is due to your airtable oauth app being in development use. In this scenario, email in airtable integration that you are trying to connect and email used in oauth app should be same

<img width="996" alt="Screenshot 2024-10-29 at 11 08 32 AM" src="https://github.com/user-attachments/assets/268afbbd-c38e-4c03-97b9-77ecbeaf80f5">

But in order to use other emails as well, you would need to fill these information in your oauth app settings 😊

**Comment by jobenjada** [comment]
@domibarton does this solve it? if so pls close the issue :)

**Comment by domibarton** [comment]
> [@domibarton](https://github.com/domibarton) any updates ?

I'll check and let you know today :)

**Comment by Dhruwang** [comment]
Hey @domibarton , if it works, can you please close this one ? 😊

**Comment by mattinannt** [comment]
Closing this due to inactivity :-)
