### ISSUE TITLE
The column `Invite.deprecatedRole` does not exist in DB

### ISSUE THREAD

**Issue by satonotdead** [formbricks/formbricks#4294]
### Issue Summary

When I try to [migrate](https://formbricks.com/docs/self-hosting/migration-guide) in order to use the last version of Formbricks, I see this error:

```
  23 await prisma.$transaction(
  24   async (transactionPrisma) => {
  25     // Fetch all invites and group them by organizationId
→ 26     const invites = (await transactionPrisma.invite.findMany(
The column `Invite.deprecatedRole` does not exist in the current database.
    at Mn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7753)
    at Mn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7061)
    at Mn.request (/app/node_modules/@prisma/client/runtime/library.js:121:6745)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async prisma.$transaction.timeout (/app/packages/database/data-migrations/20241107161932_add_teams/data-migration.ts:26:24)
    at async Proxy._transactionWithCallback (/app/node_modules/@prisma/client/runtime/library.js:130:8000)
    at async runMigration (/app/packages/database/data-migrations/XXXXXXXXX_add_teams/data-migration.ts:23:3) {
  code: 'P2022',
  clientVersion: '5.20.0',
  meta: { modelName: 'Invite', column: 'Invite.deprecatedRole' }
}
```

### Expected Behavior

Fix the database and/or skip the validation because I'm not using invites.

### Your Environment

Self-hosted Formbricks

**Comment by saschafoerster** [comment]
Have the same issue. 

```
formbricks-1  | 
formbricks-1  | 99 migrations found in prisma/migrations
formbricks-1  | 
formbricks-1  | Error: P3009
formbricks-1  | 
formbricks-1  | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
formbricks-1  | The `20241017124431_add_documents_and_insights` migration started at 2024-11-09 07:00:51.745162 UTC failed
formbricks-1  | 
formbricks-1  | 
postgres-1    | 2024-11-14 21:58:59.405 UTC [84] LOG:  could not receive data from client: Connection reset by peer
formbricks-1  | npm error Lifecycle script `db:migrate:deploy` failed with error:
formbricks-1  | npm error code 1
formbricks-1  | npm error path /home/nextjs/packages/database
formbricks-1  | npm error workspace @formbricks/database@0.1.0
formbricks-1  | npm error location /home/nextjs/packages/database
formbricks-1  | npm error command failed
formbricks-1  | npm error command sh -c env DATABASE_URL="${MIGRATE_DATABASE_URL:-$DATABASE_URL}" prisma migrate deploy
```
and

```
Starting data migration...
An error occurred during migration: PrismaClientKnownRequestError: 
Invalid `transactionPrisma.invite.findMany()` invocation in
/app/packages/database/data-migrations/20241107161932_add_teams/data-migration.ts:26:55

  23 await prisma.$transaction(
  24   async (transactionPrisma) => {
  25     // Fetch all invites and group them by organizationId
→ 26     const invites = (await transactionPrisma.invite.findMany(
The column `Invite.deprecatedRole` does not exist in the current database.
    at Mn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7753)
    at Mn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7061)
    at Mn.request (/app/node_modules/@prisma/client/runtime/library.js:121:6745)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async prisma.$transaction.timeout (/app/packages/database/data-migrations/20241107161932_add_teams/data-migration.ts:26:24)
    at async Proxy._transactionWithCallback (/app/node_modules/@prisma/client/runtime/library.js:130:8000)
    at async runMigration (/app/packages/database/data-migrations/20241107161932_add_teams/data-migration.ts:23:3) {
  code: 'P2022',
  clientVersion: '5.20.0',
  meta: { modelName: 'Invite', column: 'Invite.deprecatedRole' }
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by mattinannt** [comment]
@saschafoerster @satonotdead Can you please output the logs from the postgres database.
Did you make sure you are running on a postgres database that supports the `pgvector` extension?

**Comment by saschafoerster** [comment]
I am using the new docker compose with the pgvector included: 

```
services:
  postgres:
    restart: unless-stopped
    # image: postgres:15-alpine
    image: pgvector/pgvector:pg15
    volumes:
      - ./postgres:/var/lib/postgresql/data
    <<: *environment
```

Logs: 

```
/home/formbricks# docker compose up
[+] Running 2/0
 ✔ Container formbricks-postgres-1    Created                                                                                                                   0.0s 
 ✔ Container formbricks-formbricks-1  Created                                                                                                                   0.0s 
Attaching to formbricks-1, postgres-1
postgres-1    | 
postgres-1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1    | 
postgres-1    | 2024-11-17 23:17:17.133 UTC [1] LOG:  starting PostgreSQL 15.8 (Debian 15.8-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres-1    | 2024-11-17 23:17:17.133 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1    | 2024-11-17 23:17:17.133 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1    | 2024-11-17 23:17:17.136 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1    | 2024-11-17 23:17:17.143 UTC [29] LOG:  database system was shut down at 2024-11-17 23:17:13 UTC
postgres-1    | 2024-11-17 23:17:17.169 UTC [1] LOG:  database system is ready to accept connections
formbricks-1  | 
formbricks-1  | > @formbricks/database@0.1.0 db:migrate:deploy
formbricks-1  | > env DATABASE_URL="${MIGRATE_DATABASE_URL:-$DATABASE_URL}" prisma migrate deploy
formbricks-1  | 
formbricks-1  | Prisma schema loaded from schema.prisma
formbricks-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
formbricks-1  | 
formbricks-1  | 99 migrations found in prisma/migrations
formbricks-1  | 
formbricks-1  | Error: P3009
formbricks-1  | 
formbricks-1  | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
formbricks-1  | The `20241017124431_add_documents_and_insights` migration started at 2024-11-09 07:00:51.745162 UTC failed
formbricks-1  | 
formbricks-1  | 
formbricks-1  | npm error Lifecycle script `db:migrate:deploy` failed with error:
formbricks-1  | npm error code 1
formbricks-1  | npm error path /home/nextjs/packages/database
formbricks-1  | npm error workspace @formbricks/database@0.1.0
formbricks-1  | npm error location /home/nextjs/packages/database
formbricks-1  | npm error command failed
formbricks-1  | npm error command sh -c env DATABASE_URL="${MIGRATE_DATABASE_URL:-$DATABASE_URL}" prisma migrate deploy
formbricks-1 exited with code 1
formbricks-1  | 
formbricks-1  | > @formbricks/database@0.1.0 db:migrate:deploy
formbricks-1  | > env DATABASE_URL="${MIGRATE_DATABASE_URL:-$DATABASE_URL}" prisma migrate deploy
formbricks-1  | 
formbricks-1  | Prisma schema loaded from schema.prisma
formbricks-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
formbricks-1  | 
formbricks-1  | 99 migrations found in prisma/migrations
formbricks-1  | 
formbricks-1  | Error: P3009
formbricks-1  | 
formbricks-1  | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
formbricks-1  | The `20241017124431_add_documents_and_insights` migration started at 2024-11-09 07:00:51.745162 UTC failed
formbricks-1  | 
formbricks-1  | 
formbricks-1  | npm error Lifecycle script `db:migrate:deploy` failed with error:
formbricks-1  | npm error code 1
formbricks-1  | npm error path /home/nextjs/packages/database
formbricks-1  | npm error workspace @formbricks/database@0.1.0
formbricks-1  | npm error location /home/nextjs/packages/database
formbricks-1  | npm error command failed
formbricks-1  | npm error command sh -c env DATABASE_URL="${MIGRATE_DATABASE_URL:-$DATABASE_URL}" prisma migrate deploy
formbricks-1  | 
formbricks-1  | > @formbricks/database@0.1.0 db:migrate:deploy
formbricks-1  | > env DATABASE_URL="${MIGRATE_DATABASE_URL:-$DATABASE_URL}" prisma migrate deploy
formbricks-1  | 
formbricks-1  | Prisma schema loaded from schema.prisma
formbricks-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
postgres-1    | 2024-11-17 23:17:25.614 UTC [37] LOG:  could not receive data from client: Connection reset by peer
```

**Comment by satonotdead** [comment]
> [@saschafoerster](https://github.com/saschafoerster) [@satonotdead](https://github.com/satonotdead) Can you please output the logs from the postgres database. Did you make sure you are running on a postgres database that supports the `pgvector` extension?

I can confirm the same error like @saschafoerster. I double-checked what you mentioned earlier.

**Comment by alishahlakhani** [comment]
Same :(

**Comment by satonotdead** [comment]
So, how to workaround and use the previous working version?

**Comment by jonas-hoebenreich** [comment]
Hi, I hope this helps: I successfully migrated to the latest version using these steps:

- Shut down Formbricks v2.6.
- Start Formbricks v2.7.
- Run the database migration.
- Restart Formbricks v2.7.
- Restart Redis.

I now it's stupid to start Formbricks v2.7 before the migration but the database migration actually requires some database migrations that run within Formbricks.

**Comment by saschafoerster** [comment]
At your own risk (I have backups and don't try things I don't understand WITHOUT backups): 
Your database may have a different name or user. 

```
docker compose down
docker exec -it formbricks-postgres-1 bash
psql -U postgres -d postgres
UPDATE _prisma_migrations
SET rolled_back_at = now()
WHERE migration_name = '20241017124431_add_documents_and_insights';
 \q
docker compose stop
docker compose up
```

I then got finally to where I wanted: 

```
docker compose up
[+] Running 3/3
 ✔ Network formbricks_default         Created                                                                                                                                      0.1s 
 ✔ Container formbricks-postgres-1    Created                                                                                                                                      0.1s 
 ✔ Container formbricks-formbricks-1  Created                                                                                                                                      0.1s 
Attaching to formbricks-1, postgres-1
postgres-1    | 
postgres-1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1    | 
postgres-1    | 2024-11-24 00:27:08.197 UTC [1] LOG:  starting PostgreSQL 15.8 (Debian 15.8-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres-1    | 2024-11-24 00:27:08.198 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1    | 2024-11-24 00:27:08.198 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1    | 2024-11-24 00:27:08.201 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1    | 2024-11-24 00:27:08.208 UTC [29] LOG:  database system was shut down at 2024-11-24 00:27:01 UTC
postgres-1    | 2024-11-24 00:27:08.223 UTC [1] LOG:  database system is ready to accept connections
formbricks-1  | 
formbricks-1  | > @formbricks/database@0.1.0 db:migrate:deploy
formbricks-1  | > env DATABASE_URL="${MIGRATE_DATABASE_URL:-$DATABASE_URL}" prisma migrate deploy
formbricks-1  | 
formbricks-1  | Prisma schema loaded from schema.prisma
formbricks-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
formbricks-1  | 
formbricks-1  | 99 migrations found in prisma/migrations
formbricks-1  | 
formbricks-1  | Applying migration `20241017124431_add_documents_and_insights`
formbricks-1  | Applying migration `20241025105622_add_locale_to_user`
formbricks-1  | Applying migration `20241107161932_add_teams`
formbricks-1  | 
formbricks-1  | The following migration(s) have been applied:
formbricks-1  | 
formbricks-1  | migrations/
formbricks-1  |   └─ 20241017124431_add_documents_and_insights/
formbricks-1  |     └─ migration.sql
formbricks-1  |   └─ 20241025105622_add_locale_to_user/
formbricks-1  |     └─ migration.sql
formbricks-1  |   └─ 20241107161932_add_teams/
formbricks-1  |     └─ migration.sql
formbricks-1  |       
formbricks-1  | All migrations have been successfully applied.
formbricks-1  | npm notice
formbricks-1  | npm notice New minor version of npm available! 10.8.2 -> 10.9.1
formbricks-1  | npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.1
formbricks-1  | npm notice To update run: npm install -g npm@10.9.1
formbricks-1  | npm notice
formbricks-1  |   ▲ Next.js 14.2.16
formbricks-1  |   - Local:        http://localhost:3000
formbricks-1  |   - Network:      http://0.0.0.0:3000
formbricks-1  | 
formbricks-1  |  ✓ Starting...
formbricks-1  |  ✓ Ready in 577ms
^CGracefully stopping... (press Ctrl+C again to force)
```

Solution: 
I had watchtower own. So the upgrade to 2.7.0 was tried with a database, that was not yet vector-ready. When changing it to pgvector, the migration still had a status of being broken because of that. When you reset the migration and then start into an pgvector postgresql, the migration works as expected. 

So, either, you don't work with auto-updates like watchtower OR you have to live with the fact, that updates may break stuff. 
I keep watchtower running and I hope, that the next migrations run smoothly. :)

**Comment by satonotdead** [comment]
Thanks for your following up. I tried
> psql -U postgres -d postgres
> UPDATE _prisma_migrations
But it gives:
```
ERROR:  relation "_prisma_migrations" does not exist
LINE 1: UPDATE _prisma_migrations

```

**Comment by saschafoerster** [comment]
Try @satonotdead 
`psql -U postgres -d formbricks`
That's why I said, the database name has to be checked. ;) They changed it later on, but I stayed with the early naming.

**Comment by satonotdead** [comment]
Hey, I think my issue was not with the database (I get logged into postgres user within the container) but with their records.

It seems that `_prisma_migrations` didn't exist on my instance?

**Comment by mattinannt** [comment]
The main issue here is that the data migration was run before the database schema has been updated (that's why it is complaining about missing fields).

The schema gets auto-updated once the Formbricks 2.7 container starts. According to the logs provided by @saschafoerster this process was not complete since failing migrations were found in the database. This could be happened e.g. because the first start up failed due to pgvector not supported.
Unfortunately once this happens, it can only be resolved manually. The prisma documentation for this can be found here: https://pris.ly/d/migrate-resolve

So to roll-back the failing migration this command can be run:


```
docker run --rm \
  --network=formbricks_default \
  -e DATABASE_URL="postgresql://postgres:postgres@postgres:5432/formbricks?schema=public" \
  ghcr.io/formbricks/data-migrations:v2.7.0 \
  npx prisma migrate resolve --rolled-back "20241017124431_add_documents_and_insights"
```

After that, all containers can be restarted (`docker compose down && docker compose up -d`) and then the container should be able to start correctly and after that the data migration can be run again:

```
docker run --rm \
  --network=formbricks_default \
  -e DATABASE_URL="postgresql://postgres:postgres@postgres:5432/formbricks?schema=public" \
  -e UPGRADE_TO_VERSION="v2.7" \
  ghcr.io/formbricks/data-migrations:v2.7.0
```

**Comment by mattinannt** [comment]
We will introduce a new data migration approach with the upcoming release of Formbricks 3.0 which will solve the manual and error-prone approach of running data migrations with every release.
