### ISSUE TITLE
@formbricks/js not working with Electron

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#4480]
### Issue Summary

A user tried using `@formbricks/js` in a React app using Typescript, which is a desktop app with Electron, built with Electron-Forge (with the Webpack plugin).

He is facing the following issue running `formbricks.init`

```
js_1.default.init is not a function
    at eval (Transmutr.tsx:92:1)
    at commitHookEffectListMount (react-dom.development.js:23184:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24965:11)
    at commitPassiveMountEffects_complete (react-dom.development.js:24925:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24912:7)
    at commitPassiveMountEffects (react-dom.development.js:24900:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27073:3)
    at flushPassiveEffects (react-dom.development.js:27018:14)
    at commitRootImpl (react-dom.development.js:26969:5)
    at commitRoot (react-dom.development.js:26716:5)
```

### Expected Behavior

formbricks.init() should work without throwing an error.

### Your Environment

None

**Comment by jiminy-billy-bob** [comment]
(I am the user. If you guys have any question, I'm subscribed to this issue)

**Comment by pandeymangg** [comment]
> (I am the user. If you guys have any question, I'm subscribed to this issue)

Thanks for raising the issue 🙏 
I tried reproducing this with electron-forge, react, typescript and the webpack plugin but it works fine for me for the latest `@formbricks/js` version. Could you provide some more details about which version of the js sdk are you using and what does your tsconfig look like?
