### ISSUE TITLE
Can't download responses from a form

### ISSUE THREAD

**Issue by hjpithadia** [formbricks/formbricks#81]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Can't download responses from a form- click download csv and nothing happens, get the following message in console each time I click `Download as CSV` 

### Steps to Reproduce

1. On a completed form go to responses
2. Clicked Download
3. Cliced Download as CSV
4. Nothing happens

Here is what the console error message
```js
695-eb4a44993a5e2360.js:1 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'DsbCfK_RPK' in undefined
    at o (695-eb4a44993a5e2360.js:1:4644)
    at l (695-eb4a44993a5e2360.js:1:4906)
    at responses-7f95b7f64b81125c.js:1:7886
    at Array.map (<anonymous>)
    at responses-7f95b7f64b81125c.js:1:7855
    at s (main-088a327fef529dcb.js:1:95873)
    at Generator._invoke (main-088a327fef529dcb.js:1:95661)
    at forEach.e.<computed> [as next] (main-088a327fef529dcb.js:1:96296)
    at n (396-d3e1f8f371def37b.js:1:104808)
    at s (396-d3e1f8f371def37b.js:1:105011)
o @ 695-eb4a44993a5e2360.js:1
l @ 695-eb4a44993a5e2360.js:1
(anonymous) @ responses-7f95b7f64b81125c.js:1
(anonymous) @ responses-7f95b7f64b81125c.js:1
s @ main-088a327fef529dcb.js:1
(anonymous) @ main-088a327fef529dcb.js:1
forEach.e.<computed> @ main-088a327fef529dcb.js:1
n @ 396-d3e1f8f371def37b.js:1
s @ 396-d3e1f8f371def37b.js:1
(anonymous) @ 396-d3e1f8f371def37b.js:1
(anonymous) @ 396-d3e1f8f371def37b.js:1
(anonymous) @ responses-7f95b7f64b81125c.js:1
onClick @ responses-7f95b7f64b81125c.js:1
onClick @ 730-ee622e46ba99a02d.js:1
$e @ framework-bb5c596eafb42b22.js:1
Ye @ framework-bb5c596eafb42b22.js:1
(anonymous) @ framework-bb5c596eafb42b22.js:1
Nr @ framework-bb5c596eafb42b22.js:1
Tr @ framework-bb5c596eafb42b22.js:1
(anonymous) @ framework-bb5c596eafb42b22.js:1
Ie @ framework-bb5c596eafb42b22.js:1
(anonymous) @ framework-bb5c596eafb42b22.js:1
Fr @ framework-bb5c596eafb42b22.js:1
Jt @ framework-bb5c596eafb42b22.js:1
Zt @ framework-bb5c596eafb42b22.js:1
t.unstable_runWithPriority @ framework-bb5c596eafb42b22.js:1
Ql @ framework-bb5c596eafb42b22.js:1
Me @ framework-bb5c596eafb42b22.js:1
Xt @ framework-bb5c596eafb42b22.js:1
```

## Environment

- [x] snoopForms Cloud (app.snoopforms.com)
- [ ] self-hosted snoopForms, version/commit: [please provide]

### Additional Context

Browsers tested: 
Chrome and Firefox

**Comment by matthiasnannt** [comment]
Thank you for the bug report. We will check what's causing the issue and will have a bug ready hopefully at the end of this week 😊

**Comment by matthiasnannt** [comment]
@hjpithadia We were able to reproduce a similar error on our side and fixed it. Could you please check if your issue is fixed?
